#ifndef __KVM_ASM_OFFSETS_H__
#define __KVM_ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 */


#define SVM_vcpu_arch_regs 472 /* offsetof(struct vcpu_svm, vcpu.arch.regs) */
#define SVM_current_vmcb 7848 /* offsetof(struct vcpu_svm, current_vmcb) */
#define SVM_spec_ctrl 7896 /* offsetof(struct vcpu_svm, spec_ctrl) */
#define SVM_vmcb01 7816 /* offsetof(struct vcpu_svm, vmcb01) */
#define KVM_VMCB_pa 8 /* offsetof(struct kvm_vmcb_info, pa) */
#define SD_save_area_pa 32 /* offsetof(struct svm_cpu_data, save_area_pa) */

#define VMX_spec_ctrl 8032 /* offsetof(struct vcpu_vmx, spec_ctrl) */

#endif
